name: Trigger Tests

on:
  workflow_dispatch: # This allows us to queue from the UI
    inputs:
      test:
        description: "Some string"
        required: true
        default: ''
        type: string
      test2:
        description: 'Boolean Test'
        required: true
        default: true
        type: boolean
      test3:
        description: 'breaking test'
        required: true
        default: '4th option'
        type: choice
        options:
          - wow
          - cool
          - "interesting"


jobs:
  namedJob:
    strategy:
      matrix:
        version: ${{ inputs.test }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        shell: bash
        run: |
          echo "Cool outputs"
          echo ${{ matrix.version }}
